### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by tdaubs** [JayBizzle/mysqldumper#10]
Hi Mark,

Nice work here! Hoping to give it out a try soon.

Just wanted to mention you might consider renaming the project to something more unique since there is already a mysqldumper that is pretty popular. I would call it something like omnidumper or dropboxdumper or something like that so that it is unique.

Hope you the best and keep up the great work!

**Comment by JayBizzle** [comment]
Thanks for the suggestion but this tool was built for our own internal use...we just open sourced it because we thought some other devs may find it useful, so becoming popular is not our aim.

Hope you find it useful!

Thanks

**Comment by tdaubs** [comment]
Even if you have no plans to become popular... I thought you might want to rename it so it doesn't get confused with the already popular http://www.mysqldumper.net/.

**Comment by JayBizzle** [comment]
I like the current name. It does exactly what it says on the tin 👍🏻 `MySQLDumperToFTPS3orDropBox` doesn't have the same ring to it 😀
